# ============================================================
# config.ini  --  Monitor de Uso
# ============================================================

# Nome do arquivo de log (sem extensao)
# Sera salvo como: relatorios\<NomeArquivo>.log
# NomeArquivo = registro
NomeArquivo = computador_pessoal

# Pasta dos relatorios (relativo ao projeto ou caminho absoluto)
# Exemplos:
#   PastaRelatorios = relatorios
#   PastaRelatorios = C:\Users\Danilo\Documents\MonitorDeUso
PastaRelatorios = relatorios
